name: WhitelistCycle
version: '1.0'
main: com.olympicangel.whitelistcycle.main
api-version: '1.20'
authors: [OlympicAngel]
description: Allow easy mange of mutiple whitlists
commands:
  whitelistCycle:
    description: handles whitelist cycle staff
    usage: /whitelistcycle <action> <name> <group>